# Generated by Django 4.2 on 2023-05-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons_icon', models.ImageField(upload_to='static/img/news', verbose_name='Анонс-фото')),
                ('anons_text', models.CharField(max_length=400, verbose_name='Анонс-текст')),
                ('full_text', models.TextField(verbose_name='Текст новости')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
