# Generated by Django 4.2 on 2023-05-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(default=0, upload_to='static/img/news', verbose_name='Фото к новости'),
            preserve_default=False,
        ),
    ]
