# Generated by Django 4.2 on 2023-06-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_delete_attachment_rename_image_article_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='anons_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.CreateModel(
            name='ShowPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='news.article')),
            ],
        ),
    ]
