# Generated by Django 4.2 on 2023-06-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_article_anons_text_remove_article_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='anons_icon',
        ),
        migrations.AlterField(
            model_name='showphoto',
            name='photo',
            field=models.ImageField(upload_to='static/img/news/%Y%m%d%H%M%S'),
        ),
    ]
