# Generated by Django 4.2 on 2023-06-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_article_anons_icon_alter_showphoto_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
