# Generated by Django 4.2 on 2023-06-16 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/img/photos/%Y%m%d%H%M%S')),
                ('alt', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии  ',
                'ordering': ['date'],
            },
        ),
    ]
