# Generated by Django 4.2 on 2023-06-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_showphoto_delete_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='mons.jpg', upload_to='static/img/news/%Y%m%d%H%M%S', verbose_name='Картинка'),
        ),
        migrations.DeleteModel(
            name='ShowPhoto',
        ),
    ]
